Mes 240 subscribe to state
iflix/Leanplum-JavaScript-SDK pull request #8
Opened 2019-05-22 08:35 UTC by vincent-re

Fixes #
Update trackMessage
Update track
to use stored message and sdk filtering

2019-05-22 11:30 UTC, NikitaKurpas submitted a review, later dismissed

2019-05-22 11:30 UTC, NikitaKurpas commented on package.json
>      "fsevents": "^1.2.9"
Is this correct? I remember you had problems installing fsevents so that's why we moved it to optional

2019-05-22 11:30 UTC, NikitaKurpas commented on src/Leanplum.js
> +      messages: Leanplum.getFilteredResults(
Why is the message sent to `track` channel, and not `track/message` here? Is there a difference in those channels?

2019-05-22 12:31 UTC, lhoracek requested changes
I would like to see the proprietary function to be removed and only `track` to be used.

i don

2019-05-22 12:31 UTC, lhoracek commented on src/Leanplum.js
> +  static trackMessage( event, messageId) {
I don't see this whole function to be present on native SDKs and I can see only confusion when adding another name to already existent `track` and `advanceTo`. Leanplum knows only events and states (and so does business), so no need for new function from my point of view.

2019-05-23 09:22 UTC, lhoracek submitted a review, later dismissed

2019-05-23 09:36 UTC, NikitaKurpas approved these changes

2019-05-23 09:37 UTC, merged